- id: skylos-scan
  name: skylos (report only)
  entry: python -m skylos.cli
  language: python
  types_or: [python]
  pass_filenames: false
  require_serial: true
  args: [".", "--json", "--confidence", "70", "--danger"]
