from __future__ import annotations
import json
import os
from pathlib import Path
import re
import shlex
from typing import Optional, Sequence

from rich.console import Console
from rich.markup import escape

console = Console()

ANALYSIS_FLAG_MAP: dict[str, str] = {
    "dead-code": "",
    "dependency": "--sca",
    "dependencies": "--sca",
    "sca": "--sca",
    "security": "--danger",
    "quality": "--quality",
    "ai-defects": "--ai-defects",
    "ai_defects": "--ai-defects",
    "secrets": "--secrets",
}

SKYLOS_DEFENSE_RESULTS_SHELL_PATH = '"$RUNNER_TEMP/defense-results.json"'
PINNED_ACTIONS_CHECKOUT = "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5"
PINNED_ACTIONS_SETUP_PYTHON = (
    "actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065"
)
PINNED_ACTIONS_UPLOAD_ARTIFACT = (
    "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"
)
PINNED_ACTIONS_DOWNLOAD_ARTIFACT = (
    "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093"
)
PINNED_CLAUDE_CODE_ACTION = (
    "anthropics/claude-code-action@1dc994ee7a008f0ecc866d9ac23ef036b7229f84"
)

FIRST_GATED_PR_GUIDE_URL = (
    "https://github.com/duriantaco/skylos/blob/main/docs/first-gated-pr.md"
)
GATE_JOB_NAME = "Skylos Quality Gate"
DONE_JOB_NAME = "Skylos Done"
UPLOAD_JOB_NAME = "Skylos Cloud upload"
# Used when the repository's default branch cannot be read from Git.
FALLBACK_DEFAULT_BRANCHES = ("main", "master")
DEFAULT_DONE_INSTALL_COMMANDS = ("python -I -m pip install pytest",)

# Conservative: also safe inside GitHub's branch filter globs and YAML.
_BRANCH_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._/-]{0,199}")


def _installed_skylos_version() -> str | None:
    try:
        from skylos import __version__

        version = str(__version__).strip()
    except Exception:
        return None
    return version or None


def _skylos_install_command(version: str | None = None) -> str:
    # -I keeps a pull request's own files (e.g. a top-level pip/ directory)
    # off sys.path while pip runs after checkout.
    resolved = version if version is not None else _installed_skylos_version()
    if resolved and re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.!+~-]*", resolved):
        return f"python -I -m pip install {shlex.quote(f'skylos=={resolved}')}"
    return "python -I -m pip install skylos"


def _shell_path(path: str | Path | None) -> str:
    raw = str(path or ".")
    if any(ord(ch) < 32 or ord(ch) == 127 for ch in raw):
        raise ValueError("scan_path must not contain control characters")
    raw = raw.strip() or "."
    if raw.startswith("-"):
        raw = f"./{raw}"
    return shlex.quote(raw)


def is_valid_branch_name(name: str | None) -> bool:
    if not name or not _BRANCH_NAME_RE.fullmatch(name):
        return False
    return ".." not in name and not name.endswith(("/", ".lock"))


def _push_branches(default_branch: str | None) -> tuple[str, ...]:
    if default_branch is None:
        return FALLBACK_DEFAULT_BRANCHES
    if not is_valid_branch_name(default_branch):
        raise ValueError("default_branch may only contain letters, digits and . _ / -")
    return (default_branch,)


def _upload_env_block() -> str:
    return """        env:
          SKYLOS_COMMIT: ${{ github.sha }}
          SKYLOS_BRANCH: ${{ github.ref_name }}"""


def _header_comment(
    *,
    gate_on_pr: bool,
    done_job: bool,
    upload_job: bool,
    push_branches: Sequence[str],
) -> str:
    lines = [
        "# Skylos pull request gate, generated by `skylos cicd init`.",
        f"# Guide: {FIRST_GATED_PR_GUIDE_URL}",
    ]
    if gate_on_pr:
        lines += [
            "#",
            "# Pull requests (no secrets needed):",
            f'#   "{GATE_JOB_NAME}" scans the changed lines and fails when the gate fails.',
        ]
        if done_job:
            lines.append(
                f'#   "{DONE_JOB_NAME}" runs your tests and checks the change is finished.'
            )
        lines.append(
            "#   Make these required checks on your default branch to block failing PRs."
        )
    if upload_job:
        lines += [
            "#",
            f"# Pushes to {' or '.join(push_branches)}: the full scan uploads to Skylos Cloud with",
            "# GitHub OIDC (no API key secret). Cloud accepts it once the Skylos GitHub",
            "# App is installed on this repository. Without Cloud: skylos cicd init --no-upload",
        ]
    return "\n".join(lines)


def _build_done_job(
    *,
    python_version: str,
    install_command: str,
    done_install_commands: Sequence[str],
) -> str:
    project_install = "\n".join(
        f"          {command}" for command in done_install_commands
    )
    return f"""
  done:
    if: github.event_name == 'pull_request'
    name: {DONE_JOB_NAME}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout pull request head
        uses: {PINNED_ACTIONS_CHECKOUT}
        with:
          ref: ${{{{ github.event.pull_request.head.sha }}}}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: {PINNED_ACTIONS_SETUP_PYTHON}
        with:
          python-version: '{python_version}'

      - name: Install Skylos
        run: {install_command}

      # Skylos Done runs your tests itself. Edit this step if they need more.
      - name: Install project test dependencies
        run: |
{project_install}

      - name: Check the change is finished
        run: skylos done --base "origin/$GITHUB_BASE_REF"
"""


def _build_upload_job(
    *,
    python_version: str,
    install_command: str,
    scan_target: str,
    analysis_flags: str,
    baseline_flag: str,
    use_defend: bool,
) -> str:
    defend_step = ""
    if use_defend:
        defend_step = f"""
      - name: AI Defense Check and Upload
        run: skylos defend {scan_target} --fail-on critical --min-score 70 --json -o {SKYLOS_DEFENSE_RESULTS_SHELL_PATH} --upload
{_upload_env_block()}
"""
    return f"""
  cloud-upload:
    if: github.event_name == 'push' && github.ref == format('refs/heads/{{0}}', github.event.repository.default_branch)
    name: {UPLOAD_JOB_NAME}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: {PINNED_ACTIONS_CHECKOUT}
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: {PINNED_ACTIONS_SETUP_PYTHON}
        with:
          python-version: '{python_version}'

      - name: Install Skylos
        run: {install_command}

      - name: Pull Skylos Cloud Policy
        run: |
          if ! skylos sync pull; then
            echo "::error title=Skylos Cloud policy unavailable::Skylos Cloud did not accept this workflow. If this repository is not connected yet, install the Skylos GitHub App on it (step 7 of {FIRST_GATED_PR_GUIDE_URL}), or regenerate the workflow with: skylos cicd init --no-upload"
            exit 1
          fi

      - name: Scan and Upload to Skylos Cloud
        run: skylos {scan_target}{analysis_flags}{baseline_flag} --upload
{_upload_env_block()}
{defend_step}"""


def generate_workflow(
    *,
    triggers: Optional[list[str]] = None,
    analysis_types: Optional[list[str]] = None,
    python_version: str = "3.12",
    use_baseline: bool = True,
    use_llm: bool = False,
    model: Optional[str] = None,
    use_claude_security: bool = False,
    use_upload: bool = True,
    use_defend: bool = False,
    advisory_gate: bool = False,
    scan_path: str = ".",
    skylos_version: str | None = None,
    use_done: bool = True,
    done_install_commands: Optional[Sequence[str]] = None,
    default_branch: str | None = None,
) -> str:
    """
    Generate the GitHub Actions workflow YAML for Skylos scans.

    Pull requests get the "Skylos Quality Gate" job (diff-aware scan, gate,
    annotations, review comments) and, with use_done, the "Skylos Done" job.
    With use_upload, pushes to the default branch upload a full scan through
    GitHub OIDC from a separate job, the only one granted id-token: write.

    Calls: skylos/cicd/workflow.py _build_trigger_block;
        skylos/cicd/workflow.py _skylos_install_command;
        skylos/cicd/workflow.py _shell_path;
        skylos/cicd/workflow.py _build_done_job;
        skylos/cicd/workflow.py _build_upload_job;
        skylos/cicd/workflow.py _build_claude_security_jobs.

    Called from: skylos/commands/cicd_cmd.py run_cicd_command.
    """
    triggers = triggers or ["pull_request", "push"]
    analysis_types = analysis_types or [
        "dead-code",
        "security",
        "quality",
        "ai-defects",
        "secrets",
        "dependency",
    ]

    push_branches = _push_branches(default_branch)
    upload_job = use_upload and "push" in triggers
    done_job = use_done and "pull_request" in triggers
    trigger_block = _build_trigger_block(triggers, push_branches=push_branches)
    install_command = _skylos_install_command(skylos_version)
    scan_target = _shell_path(scan_path)
    analysis_flags = " ".join(
        ANALYSIS_FLAG_MAP[t]
        for t in analysis_types
        if t in ANALYSIS_FLAG_MAP and ANALYSIS_FLAG_MAP[t]
    )
    if analysis_flags:
        analysis_flags = " " + analysis_flags
    baseline_flag = " --baseline" if use_baseline else ""
    analysis_run = "\n".join(
        [
            '          if [ "${{ github.event_name }}" = "pull_request" ]; then',
            '            pr_base_ref="origin/${GITHUB_BASE_REF:-main}"',
            (
                f"            skylos {scan_target}{analysis_flags}{baseline_flag} "
                '--diff-base "$pr_base_ref" --diff "$pr_base_ref" '
                "--json -o skylos-results.json"
            ),
            "          else",
            f"            skylos {scan_target}{analysis_flags}{baseline_flag} --json -o skylos-results.json",
            "          fi",
        ]
    )

    llm_step = ""
    if use_llm:
        model_str = model or "gpt-4.1"
        api_key_env = ""
        if model_str and "claude" in model_str.lower():
            api_key_env = (
                "\n          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}"
            )
        llm_step = "\n".join(
            [
                "",
                "      - name: Skylos Agent Review (LLM)",
                "        if: github.event_name == 'pull_request'",
                (
                    f"        run: skylos agent scan {scan_target} "
                    f"--model {shlex.quote(model_str)} --changed --format json "
                    "-o skylos-llm-results.json"
                ),
                "        env:",
                "          SKYLOS_API_KEY: ${{ secrets.SKYLOS_API_KEY }}" + api_key_env,
            ]
        )
    defend_step = ""
    if use_defend:
        defend_step = "\n".join(
            [
                "",
                "      - name: AI Defense Check",
                f"        run: skylos defend {scan_target} --fail-on critical --min-score 70 --json -o {SKYLOS_DEFENSE_RESULTS_SHELL_PATH}",
            ]
        )

    review_args = ["--input skylos-results.json"]
    if use_llm:
        review_args.append("--llm-input skylos-llm-results.json")
    if use_defend:
        review_args.append(f"--defense-input {SKYLOS_DEFENSE_RESULTS_SHELL_PATH}")
    review_args.extend(['--diff-base "$pr_base_ref"', "--evidence-cards"])
    review_command = "skylos cicd review " + " ".join(review_args)
    review_run = "\n".join(
        [
            '          pr_base_ref="origin/${GITHUB_BASE_REF:-main}"',
            f"          {review_command}",
        ]
    )
    skylos_environment = "\n    environment: skylos-security" if use_llm else ""
    # The upload job owns default-branch pushes; the gate job covers the rest.
    gate_condition = "\n    if: github.event_name != 'push'" if upload_job else ""
    gate_advisory_flag = " --advisory" if advisory_gate else ""

    header = _header_comment(
        gate_on_pr="pull_request" in triggers,
        done_job=done_job,
        upload_job=upload_job,
        push_branches=push_branches,
    )

    workflow = f"""{header}
name: Skylos Analysis

{trigger_block}

permissions:
  contents: read

jobs:
  skylos:{gate_condition}
    name: {GATE_JOB_NAME}
    runs-on: ubuntu-latest
    timeout-minutes: 15{skylos_environment}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: {PINNED_ACTIONS_CHECKOUT}
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: {PINNED_ACTIONS_SETUP_PYTHON}
        with:
          python-version: '{python_version}'

      - name: Install Skylos
        run: {install_command}

      - name: Run Skylos Analysis
        run: |
{analysis_run}
{llm_step}{defend_step}
      - name: Quality Gate
        if: always()
        run: skylos cicd gate --input skylos-results.json --summary{gate_advisory_flag}

      - name: GitHub Annotations
        if: always()
        run: skylos cicd annotate --input skylos-results.json

      - name: PR Review Comments
        if: github.event_name == 'pull_request' && always()
        run: |
{review_run}
        env:
          GH_TOKEN: ${{{{ github.token }}}}
{
        ""
        if not use_claude_security
        else f'''
      - name: Upload Skylos Results for Cross-Reference
        if: always()
        uses: {PINNED_ACTIONS_UPLOAD_ARTIFACT}
        with:
          name: skylos-results
          path: skylos-results.json
          if-no-files-found: error
'''
    }"""

    if done_job:
        workflow += _build_done_job(
            python_version=python_version,
            install_command=install_command,
            done_install_commands=tuple(
                done_install_commands or DEFAULT_DONE_INSTALL_COMMANDS
            ),
        )

    if upload_job:
        workflow += _build_upload_job(
            python_version=python_version,
            install_command=install_command,
            scan_target=scan_target,
            analysis_flags=analysis_flags,
            baseline_flag=baseline_flag,
            use_defend=use_defend,
        )

    if use_claude_security:
        workflow += _build_claude_security_jobs(python_version, install_command)

    return workflow


def _build_claude_security_jobs(python_version: str, install_command: str) -> str:
    return f"""
  claude-security:
    runs-on: ubuntu-latest
    environment: skylos-security
    steps:
      - name: Checkout
        uses: {PINNED_ACTIONS_CHECKOUT}
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Claude Code Security Review
        uses: {PINNED_CLAUDE_CODE_ACTION}
        with:
          anthropic_api_key: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          direct_prompt: "/review --output-file claude-security-results.json"

      - name: Upload Claude Security Results
        if: always()
        uses: {PINNED_ACTIONS_UPLOAD_ARTIFACT}
        with:
          name: claude-security-results
          path: claude-security-results.json
          if-no-files-found: error

  upload-claude-findings:
    if: always() && needs.skylos.result != 'skipped'
    runs-on: ubuntu-latest
    needs: [skylos, claude-security]
    steps:
      - name: Checkout
        uses: {PINNED_ACTIONS_CHECKOUT}
        with:
          persist-credentials: false

      - name: Setup Python
        uses: {PINNED_ACTIONS_SETUP_PYTHON}
        with:
          python-version: '{python_version}'

      - name: Install Skylos
        run: {install_command}

      - name: Download Claude Security Results
        uses: {PINNED_ACTIONS_DOWNLOAD_ARTIFACT}
        with:
          name: claude-security-results

      - name: Download Skylos Results
        uses: {PINNED_ACTIONS_DOWNLOAD_ARTIFACT}
        with:
          name: skylos-results

      - name: Ingest Claude Security Findings
        run: skylos ingest claude-security --input claude-security-results.json --cross-reference skylos-results.json
"""


def _build_trigger_block(
    triggers: list[str], *, push_branches: Sequence[str] = FALLBACK_DEFAULT_BRANCHES
) -> str:
    lines = ['"on":']
    for trigger in triggers:
        if trigger == "pull_request":
            # Every pull request, whatever its base branch.
            lines.append("  pull_request:")
        elif trigger == "push":
            # Only the default branch: a push run on a PR branch would add
            # skipped twins of the PR checks to the same commit.
            branches = ", ".join(json.dumps(branch) for branch in push_branches)
            lines.append("  push:")
            lines.append(f"    branches: [{branches}]")
        elif trigger == "schedule":
            lines.append("  schedule:")
            lines.append("    - cron: '0 6 * * 1'  # Weekly Monday 6am")
        elif trigger == "workflow_dispatch":
            lines.append("  workflow_dispatch:")
        else:
            lines.append(f"  {trigger}:")
    return "\n".join(lines)


def write_workflow(content: str, output_path: str):
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        shown = os.path.relpath(path)
    except ValueError:
        shown = str(path)
    shown = escape(shown)

    if path.exists():
        console.print(
            f"[yellow]Overwriting existing workflow: {shown}[/yellow]", soft_wrap=True
        )

    path.write_text(content)
    console.print(
        f"[bold green]Workflow written to {shown}[/bold green]", soft_wrap=True
    )
