import * as vscode from "vscode";
import type { FindingsStore } from "./store";
import type { SkylosFinding } from "./types";
import { computeSecurityScore } from "./dashboard";
import { getRuleMeta } from "./rules";

export async function exportReport(store: FindingsStore): Promise<void> {
  const pick = await vscode.window.showQuickPick(
    [
      { label: "Markdown", description: "Human-readable report", format: "md" as const },
      { label: "JSON", description: "Machine-readable report", format: "json" as const },
      { label: "SARIF", description: "For CI/code-scanning (GitHub, GitLab, Azure DevOps)", format: "sarif" as const },
    ],
    { placeHolder: "Export format" },
  );
  if (!pick)
    return;

  let content: string;
  let lang: string;

  if (pick.format === "md") {
    content = buildMarkdown(store);
    lang = "markdown";
  } else if (pick.format === "sarif") {
    content = buildSarif(store);
    lang = "json";
  } else {
    content = buildJson(store);
    lang = "json";
  }

  const doc = await vscode.workspace.openTextDocument({ content, language: lang });
  await vscode.window.showTextDocument(doc);
}

function getProjectName(): string {
  const ws = vscode.workspace.workspaceFolders?.[0];
  return ws?.name ?? "Unknown Project";
}

function buildMarkdown(store: FindingsStore): string {
  const { score, grade } = computeSecurityScore(store, "raw");
  const counts = store.countBySeverity("raw");
  const catCounts = store.countByCategory("raw");
  const findings = store.getAllRawFindings();
  const date = new Date().toISOString().split("T")[0];

  let md = `# Skylos Security Report\n\n`;
  md += `**Project:** ${getProjectName()}  \n`;
  md += `**Date:** ${date}  \n`;
  md += `**Score:** ${grade} (${score}/100)\n\n`;

  md += `## Summary\n\n`;
  md += `| Severity | Count |\n|----------|-------|\n`;
  for (const sev of ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]) {
    const c = counts[sev] ?? 0;
    if (c > 0) md += `| ${sev} | ${c} |\n`;
  }
  md += `\n`;

  md += `## Categories\n\n`;
  for (const [cat, count] of Object.entries(catCounts)) {
    md += `- **${cat}**: ${count}\n`;
  }
  md += `\n`;

  const grouped = new Map<string, typeof findings>();
  for (const f of findings) {
    const list = grouped.get(f.category) ?? [];
    list.push(f);
    grouped.set(f.category, list);
  }

  md += `## Findings\n\n`;
  for (const [cat, items] of grouped) {
    md += `### ${cat}\n\n`;
    for (const f of items) {
      const meta = getRuleMeta(f.ruleId);
      const shortFile = f.file.split("/").slice(-2).join("/");
      md += `- **[${f.ruleId}]** ${f.message} — \`${shortFile}:${f.line}\` (${f.severity})`;
      if (meta?.owasp) md += `  OWASP: ${meta.owasp}`;
      if (meta?.cwe) md += `  ${meta.cwe}`;
      if (meta?.fix) md += `\n  > Fix: ${meta.fix}`;
      md += `\n`;
    }
    md += `\n`;
  }

  md += `---\n*Generated by Skylos*\n`;
  return md;
}

function buildJson(store: FindingsStore): string {
  const { score, grade } = computeSecurityScore(store, "raw");
  const counts = store.countBySeverity("raw");
  const findings = store.getAllRawFindings();
  const date = new Date().toISOString().split("T")[0];

  const report = {
    report: {
      project: getProjectName(),
      date,
      score: { value: score, grade },
      summary: counts,
      findings: findings.map((f) => {
        const meta = getRuleMeta(f.ruleId);
        return {
          ruleId: f.ruleId,
          severity: f.severity,
          category: f.category,
          message: f.message,
          file: f.file,
          line: f.line,
          owasp: meta?.owasp ?? null,
          cwe: meta?.cwe ?? null,
          fix: meta?.fix ?? null,
        };
      }),
    },
  };

  return JSON.stringify(report, null, 2);
}

function buildSarif(store: FindingsStore): string {
  const findings = store.getAllRawFindings();
  const ws = vscode.workspace.workspaceFolders?.[0];
  const wsRoot = ws?.uri.fsPath ?? "";

  const ruleIds = [...new Set(findings.map((f) => f.ruleId))];
  const rules = ruleIds.map((id) => {
    const meta = getRuleMeta(id);
    const rule: Record<string, unknown> = {
      id,
      name: meta?.name ?? id,
      shortDescription: { text: meta?.description ?? id },
    };
    if (meta?.fix) {
      rule.help = { text: meta.fix, markdown: meta.fix };
    }
    const tags: string[] = [];
    if (meta?.cwe) tags.push(meta.cwe);
    if (meta?.owasp) tags.push(`OWASP:${meta.owasp}`);
    if (meta?.pciDss) tags.push(`PCI-DSS:${meta.pciDss}`);
    if (tags.length > 0) {
      rule.properties = { tags };
    }
    return rule;
  });

  const ruleIndex = new Map(ruleIds.map((id, i) => [id, i]));

  const results = findings.map((f) => {
    const relPath = f.file.startsWith(wsRoot) ? f.file.slice(wsRoot.length + 1) : f.file;
    return {
      ruleId: f.ruleId,
      ruleIndex: ruleIndex.get(f.ruleId) ?? 0,
      level: sarifLevel(f),
      message: { text: f.message },
      locations: [
        {
          physicalLocation: {
            artifactLocation: { uri: relPath, uriBaseId: "%SRCROOT%" },
            region: { startLine: Math.max(1, f.line), startColumn: Math.max(1, f.col) },
          },
        },
      ],
    };
  });

  const sarif = {
    $schema: "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
    version: "2.1.0",
    runs: [
      {
        tool: {
          driver: {
            name: "Skylos",
            informationUri: "https://github.com/duriantaco/skylos",
            rules,
          },
        },
        results,
        originalUriBaseIds: wsRoot ? { "%SRCROOT%": { uri: `file://${wsRoot}/` } } : undefined,
      },
    ],
  };

  return JSON.stringify(sarif, null, 2);
}

function sarifLevel(f: SkylosFinding): string {
  const s = f.severity.toUpperCase();
  if (s === "CRITICAL" || s === "HIGH") 
    return "error";
  if (s === "MEDIUM" || s === "WARN") 
    return "warning";
  return "note";
}
