import * as vscode from "vscode";
import type { FindingsStore } from "./store";
import { computeSecurityScore } from "./dashboard";
import { getRuleMeta } from "./rules";

export async function exportReport(store: FindingsStore): Promise<void> {
  const pick = await vscode.window.showQuickPick(
    [
      { label: "Markdown", description: "Human-readable report", format: "md" as const },
      { label: "JSON", description: "Machine-readable report", format: "json" as const },
    ],
    { placeHolder: "Export format" },
  );
  if (!pick) 
    return;

  const content = pick.format === "md" ? buildMarkdown(store) : buildJson(store);
  const lang = pick.format === "md" ? "markdown" : "json";

  const doc = await vscode.workspace.openTextDocument({ content, language: lang });
  await vscode.window.showTextDocument(doc);
}

function getProjectName(): string {
  const ws = vscode.workspace.workspaceFolders?.[0];
  return ws?.name ?? "Unknown Project";
}

function buildMarkdown(store: FindingsStore): string {
  const { score, grade } = computeSecurityScore(store);
  const counts = store.countBySeverity();
  const catCounts = store.countByCategory();
  const findings = store.getAllFindings();
  const date = new Date().toISOString().split("T")[0];

  let md = `# Skylos Security Report\n\n`;
  md += `**Project:** ${getProjectName()}  \n`;
  md += `**Date:** ${date}  \n`;
  md += `**Score:** ${grade} (${score}/100)\n\n`;

  md += `## Summary\n\n`;
  md += `| Severity | Count |\n|----------|-------|\n`;
  for (const sev of ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]) {
    const c = counts[sev] ?? 0;
    if (c > 0) md += `| ${sev} | ${c} |\n`;
  }
  md += `\n`;

  md += `## Categories\n\n`;
  for (const [cat, count] of Object.entries(catCounts)) {
    md += `- **${cat}**: ${count}\n`;
  }
  md += `\n`;

  const grouped = new Map<string, typeof findings>();
  for (const f of findings) {
    const list = grouped.get(f.category) ?? [];
    list.push(f);
    grouped.set(f.category, list);
  }

  md += `## Findings\n\n`;
  for (const [cat, items] of grouped) {
    md += `### ${cat}\n\n`;
    for (const f of items) {
      const meta = getRuleMeta(f.ruleId);
      const shortFile = f.file.split("/").slice(-2).join("/");
      md += `- **[${f.ruleId}]** ${f.message} — \`${shortFile}:${f.line}\` (${f.severity})`;
      if (meta?.owasp) md += `  OWASP: ${meta.owasp}`;
      if (meta?.cwe) md += `  ${meta.cwe}`;
      if (meta?.fix) md += `\n  > Fix: ${meta.fix}`;
      md += `\n`;
    }
    md += `\n`;
  }

  md += `---\n*Generated by Skylos*\n`;
  return md;
}

function buildJson(store: FindingsStore): string {
  const { score, grade } = computeSecurityScore(store);
  const counts = store.countBySeverity();
  const findings = store.getAllFindings();
  const date = new Date().toISOString().split("T")[0];

  const report = {
    report: {
      project: getProjectName(),
      date,
      score: { value: score, grade },
      summary: counts,
      findings: findings.map((f) => {
        const meta = getRuleMeta(f.ruleId);
        return {
          ruleId: f.ruleId,
          severity: f.severity,
          category: f.category,
          message: f.message,
          file: f.file,
          line: f.line,
          owasp: meta?.owasp ?? null,
          cwe: meta?.cwe ?? null,
          fix: meta?.fix ?? null,
        };
      }),
    },
  };

  return JSON.stringify(report, null, 2);
}
